Feature/particle implementation
thales-markets/thales-sport-markets pull request #369
Opened 2023-12-27 14:02 UTC by Gorshtak

2023-12-27 15:10 UTC, lotinasa submitted a review, later dismissed

2023-12-27 15:10 UTC, lotinasa commented on src/pages/AARelatedPages/Withdraw/Withdraw.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
Can be removed

2023-12-27 15:10 UTC, lotinasa commented on src/pages/AARelatedPages/Withdraw/components/WithdrawalConfirmationModal/WithdrawalConfirmationModal.tsx
> +    // useEffect(() => {
Just temporary or forgotten?

2023-12-27 15:10 UTC, lotinasa commented on src/pages/Profile/components/MyPortfolio/MyPortfolio.tsx
> +        <>
can be removed

2023-12-27 15:10 UTC, lotinasa commented on src/pages/Root/Provider/ParticleProvider/ParticleProvider.tsx
> +                        { id: 10, name: 'optimism' },
Network IDs can be replaced with enum values e.g. Network.OptimismMainnet

2023-12-27 18:49 UTC, Gorshtak commented on src/components/ConnectWalletModal/ConnectWalletModal.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
Not sure, will put them in dependency array and remove the comment for disabling eslint

2023-12-27 18:53 UTC, Gorshtak commented on src/pages/AARelatedPages/Deposit/Deposit.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
Not sure, added it back and changed the logic a little bit, should be tested before merging

2023-12-27 19:10 UTC, Gorshtak commented on src/pages/AARelatedPages/Deposit/Deposit.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
Not sure, but removed selectedToken from dependencies as this should only be checked for selectedTokenFromUrl

2023-12-27 19:10 UTC, Gorshtak commented on src/pages/AARelatedPages/Withdraw/Withdraw.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
Removed it from dependencies and from if statement

2023-12-27 19:15 UTC, Gorshtak commented on src/pages/AARelatedPages/Withdraw/components/WithdrawalConfirmationModal/WithdrawalConfirmationModal.tsx
> +    // useEffect(() => {
Will be needed for biconomy AA

2023-12-28 08:00 UTC, vpoklopic requested changes

2024-01-03 12:40 UTC, vpoklopic approved these changes

2024-01-03 13:48 UTC, vpoklopic submitted a review, later dismissed

2024-01-03 14:55 UTC, vpoklopic approved these changes

2024-01-03 16:14 UTC, merged