Multicall on batch txs for claiming positions
thales-markets/thales-sport-markets pull request #929
Opened 2024-09-17 11:38 UTC by makiBaraba

2024-09-17 11:41 UTC, vladanthales requested changes

2024-09-17 11:41 UTC, vladanthales commented on src/constants/network.ts
> +export const GAS_BUFFER_FOR_CLAIM_BATCH = 1.1;
Please use the existing buffer that we have 1.2 is also ok here.

2024-09-17 11:41 UTC, vladanthales commented on src/pages/Profile/components/OpenClaimableTickets/OpenClaimableTickets.tsx
> +    // const claimCollateralAddress = useMemo(
Remove commented code

2024-09-17 11:41 UTC, vladanthales commented on src/pages/Profile/components/OpenClaimableTickets/OpenClaimableTickets.tsx
> +    // const isEth = claimCollateralAddress === ZERO_ADDRESS;
Remove commented code

2024-09-17 11:54 UTC, vladanthales approved these changes

2024-09-18 09:07 UTC, lotinasa commented on src/pages/Profile/components/OpenClaimableTickets/OpenClaimableTickets.tsx
> +                            const _tx = await sportsAMMV2ContractWithSigner.populateTransaction.exerciseTicket(
No need for underscore in _tx variable name.

2024-09-18 09:40 UTC, lotinasa approved these changes

2024-09-18 10:05 UTC, merged